/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Layout from "../components/Layout";
import HeroSection from "../components/HeroSection";
import FeatureSection from "../components/FeatureSection";
import InvitationSection from "../components/InvitationSection";
import ContactMatchSection from "../components/ContactMatchSection";
import GoogleCalSection from "../components/GoogleCalSection";
import CallToAction from "../components/CallToAction";

const Home: React.FC = () => {
  return (
    <Layout>
      <HeroSection />
      <FeatureSection />
      <InvitationSection />
      <ContactMatchSection />
      <GoogleCalSection />
      <CallToAction />
    </Layout>
  );
};

export default Home;
