/**
 * This code was generated by Builder.io.
 */
import React, { useState } from "react";
import { Link } from "react-router-dom";
import VideoModal from "./VideoModal";

const CallToAction: React.FC = () => {
  const [isOpen, setOpen] = useState(false);

  return (
    <section className="flex justify-center items-center w-full max-md:max-w-full py-40 max-md:pb-0">
      <div className="flex flex-col justify-center items-center w-full max-w-[75rem] h-[50rem] max-md:max-w-full max-md:h-[33.75rem]">
        <h3 className="self-stretch text-4xl font-medium text-center text-white max-md:max-w-full max-md:text-2xl max-md:leading-normal">
          Start scheduling with Aivee
        </h3>
        <Link to={'https://emkd1hav7wo.typeform.com/to/SlakC6t7'} target="_blank">
          <button className="justify-center px-[2.625rem] py-[0.75rem] text-xl font-semibold bg-emerald-200 rounded-[100px] text-zinc-950 max-md:px-8 mt-12 max-md:mt-6" type="button">
            Join Waitlist
          </button>
        </Link>
      </div>
      <VideoModal isOpen={isOpen} close={() => setOpen(!isOpen)}/>
    </section>
  );
};

export default CallToAction;
