/**
 * This code was generated by Builder.io.
 */
import React from "react";

const FeatureSection: React.FC = () => {
  return (
    <section className="flex justify-center items-center w-full max-md:max-w-full">
      <div className="w-full max-w-[75rem] max-h-[50rem] max-md:max-w-full px-12 py-10 max-md:px-10 max-md:py-12">
        <div className="flex gap-[6.25rem] max-md:flex-col max-md:gap-0">
          <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
            <div className="flex flex-col self-stretch my-auto font-semibold max-md:mt-10 max-md:max-w-full">
              <h2 className="text-[1.875rem] max-md:text-xl text-emerald-200 max-md:max-w-full">
                Instant Event Creation
              </h2>
              <h3 className="mt-5 text-4xl leading-normal text-white max-md:max-w-full max-md:text-2xl">
                Transform Your Screenshots into Engaging Events!
              </h3>
            </div>
          </div>
          <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
            <div className="flex flex-col grow max-md:mt-10 max-md:max-w-full">
              <img
                loading="lazy"
                src="/aivee_homepage_02.png"
                alt=""
                className="w-full backdrop-blur-2xl max-md:max-w-full"
              />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default FeatureSection;
