/**
 * This code was generated by Builder.io.
 */
import React from "react";

const FeatureSection: React.FC = () => {
  return (
    <section className="flex justify-center items-center w-full max-md:max-w-full mb-[6.25rem]">
      <div className="w-full max-w-[75rem] max-h-[50rem] max-md:max-w-full">
        <div className="flex gap-[6.25rem] max-md:flex-col max-md:gap-0">
          <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
            <div className="flex flex-col grow max-md:mt-10 max-md:max-w-full">
              <img
                loading="lazy"
                src="/aivee_ss_uploading.svg"
                alt=""
                className="w-full backdrop-blur-2xl max-md:max-w-full"
              />
            </div>
          </div>
          <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
            <div className="flex flex-col self-stretch my-auto max-md:mt-10 max-md:max-w-full">
              <span className="text-emerald-200 border-[1px] border-emerald-200 rounded-[3.125rem] w-fit px-4 py-[0.625rem] gap-[0.625rem] text-[1rem] font-normal leading-normal">Screenshot Upload</span>
              <h2 className="text-[3.5rem] font-medium leading-[4.5rem] max-md:text-xl max-md:max-w-full my-[1.38rem]">
                <span className="gradient-text">Schedule</span> anything with a screenshot
              </h2>
              <h3 className="text-[1.25rem] font-normal leading-normal opacity-60 text-white max-md:max-w-full">
              Upload any screenshot—conversation, flight, reservation, yoga class, or accommodations—and Aivee will handle the rest.
              </h3>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default FeatureSection;
