/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Footer: React.FC = () => {
  return (
    <footer className="flex relative justify-center items-center w-full text-emerald-200 backdrop-blur-[80px] bg-zinc-950 bg-opacity-20 max-md:max-w-full">
      <div className="flex gap-5 justify-between w-full max-w-[75rem] px-12 pt-8 pb-10 text-[1rem] font-normal max-md:flex-wrap max-md:max-w-full max-md:flex-col max-md:content-center">
        <address className="flex not-italic text-xl max-md:text-base">
          <a href="mailto:hello@aivee.xyz" className="text-inherit">
            Contact: hello@aivee.xyz
          </a>
        </address>
        <div className="flex flex-col justify-center text-xl max-md:text-base max-md:text-center">
          <a href="/privacy-policy" className="text-inherit">Privacy Policy</a>
          <a href="/terms-of-use" className="mt-2 text-inherit">Terms of use</a>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
