/**
 * This code was generated by Builder.io.
 */
import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";

const Header: React.FC = () => {
  const [typeform, setTypeform] = useState('');
  const [scrollClass, setScrollClass] = useState('');

  const handleScroll = () => {
    if (window.scrollY > 100) {
      setScrollClass('bg-zinc-950 backdrop-blur-[50px] bg-opacity-10');
    } else {
      setScrollClass('');
    }
  }

  useEffect(() => {
    window.addEventListener('scroll', handleScroll);
    const timer = setInterval(() => {
      setTypeform(localStorage.getItem('typeform_url') || '');
    }, 1000);

    return () => {
      window.removeEventListener('scroll', handleScroll);
      clearInterval(timer);
    }
  }, [])

  return (
    <nav className={`flex justify-center items-center w-full font-semibold max-h-24 sticky top-0 z-50 max-md:max-h-[4.75rem] ${scrollClass}`}>
      <div className="flex gap-0 justify-between items-center content-center max-md:flex-wrap w-full py-4 px-[4.5rem] max-md:px-[1.25rem]">
        <div className="text-4xl text-white whitespace-nowrap max-md:flex-wrap">
          <Link className="flex flex-1 gap-2.5" to={'/'}>
            <img
              loading="lazy"
              src="/aivee.png"
              alt=""
              className="shrink-0 aspect-square h-12 max-md:h-9"
            />
            <div className="my-auto text-xl max-md:max-w-full max-md:text-lg">Aivee</div>
          </Link>
        </div>
        <Link to={typeform} target="_blank">
          <span className="justify-center px-[2.625rem] py-[0.75rem] my-auto text-base max-h-[3.25rem] bg-emerald-200 rounded-[3.125rem] text-zinc-950 max-md:text-base max-md:max-h-6 max-md:py-[0.6rem] max-md:px-6">
            Join Waitlist
          </span>
        </Link>
      </div>
    </nav>
  );
};

export default Header;
