/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Header: React.FC = () => {
  return (
    <header className="flex justify-center items-center px-16 py-10 w-full font-semibold bg-zinc-950 max-md:px-5 max-md:max-w-full">
      <div className="flex gap-0 justify-between max-md:flex-wrap w-full max-w-[1440px] max-md:max-w-full">
        <div className="flex flex-1 gap-2.5 text-4xl text-white whitespace-nowrap max-md:flex-wrap">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/198ad601a8df0fb10d08d08d841fba6dece38c5029d8cc95d69465757286e436?apiKey=c6fdaf582f1c400daeb8eaaff6846c8c&"
            alt=""
            className="shrink-0 aspect-square w-[87px]"
          />
          <div className="my-auto max-md:max-w-full">AiVee</div>
        </div>
        <button className="justify-center px-10 py-3 my-auto text-2xl bg-emerald-200 rounded-[100px] text-zinc-950 max-md:px-5">
          Join Waitlist
        </button>
      </div>
    </header>
  );
};

export default Header;
