/**
 * This code was generated by Builder.io.
 */
import React from "react";

const HeroSection: React.FC = () => {
  return (
    <section className="flex justify-center items-center w-full max-md:max-w-full">
      <div className="w-full max-w-[75rem] max-h-[50rem] max-md:max-w-full px-12 py-10 max-md:px-10 max-md:py-12">
        <div className="flex gap-[6.25rem] max-xl:gap-20 max-md:flex-col">
          <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
            <div className="flex flex-col self-stretch pr-3 my-auto font-semibold max-md:mt-10 max-md:max-w-full">
              <h2 className="text-[1.875rem] max-md:text-xl text-emerald-200 max-md:max-w-full">
                AI-Powered Smart Scheduling
              </h2>
              <h1 className="mt-5 text-4xl leading-normal text-white max-md:max-w-full max-md:text-2xl font-semibold">
                Effortlessly Plan with Just a Screenshot
              </h1>
            </div>
          </div>
          <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
            <div className="flex flex-col grow max-md:mt-10 max-md:max-w-full">
              <img
                loading="lazy"
                src="/aivee_homepage_01.png"
                alt=""
                className="w-full backdrop-blur-2xl max-md:max-w-full"
              />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default HeroSection;
