/**
 * This code was generated by Builder.io.
 */
import React from "react";

const InvitationSection: React.FC = () => {
  return (
    <section className="flex justify-center items-center px-16 py-20 w-full max-md:px-5 max-md:max-w-full">
      <div className="w-full max-w-[1440px] max-md:max-w-full">
        <div className="flex gap-40 max-xl:gap-20 max-md:flex-col max-md:gap-0">
          <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
            <div className="flex flex-col justify-center self-stretch my-auto max-md:mt-10 max-md:max-w-full">
              <h2 className="text-4xl max-md:text-xl font-semibold text-emerald-200 max-md:max-w-full">
                Streamlined Invitations
              </h2>
              <h3 className="mt-5 text-[44px] leading-normal font-medium text-white max-md:max-w-full max-md:text-2xl">
                Effortlessly Manage <br/>Invitees Straight from Your Contact List!
              </h3>
            </div>
          </div>
          <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
            <div className="flex flex-col grow max-md:mt-10 max-md:max-w-full">
              <img
                loading="lazy"
                src="/aivee_homepage_03.png"
                alt=""
                className="w-full backdrop-blur-2xl max-md:max-w-full"
              />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default InvitationSection;
